uavblog/posts/forms.py
'''importing the relevant dependencies'''
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired




'''creating the post information'''
class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')


uavblog/main/routes.py
'''importing the relevant dependencies'''
from flask import render_template, request, Blueprint
from uavblog.models import Post



#creating an instance of the blueprint just like for the flask app
main = Blueprint('main', __name__)

@main.route("/")#decorators using the init in the uavblog
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)#page is an optional parameter in the url,default page is set to one and the int dictates that if a person wants a page no thyen it must be equal to an interger
    #posts = Post.query.all()#grabbing all the post from the database
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page = page,per_page=5)#this allows you to specify the no of posts you want to display per page and this enhances the speed of your page and is a flask sqlalchemy module
    #the order_by in the post alows you to be able to arrange the posts allowing the latest post to be at the top
    return render_template ("home.html")

@main.route("/about")
def about():
	return render_template("about.html",title = "About")




uavblog/posts/__init__.py
#this makes python understand that this is a package

uavblog/posts/routes.py
'''importing the relevant dependencies'''
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from uavblog import db
from uavblog.models import Post
from uavblog.posts.forms import PostForm


#creating an instance of the blueprint just like for the flask app
posts = Blueprint('posts', __name__)


#the instance of the route is now specific to this post
@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)#adding a post to a database
        db.session.commit()
        flash('Your post has been created!', 'success')#category of success
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')    

@posts.route("/post/<int:post_id>")#this is allowed in flask to allow us to query a route by the id 
def post(post_id):
    post = Post.query.get_or_404(post_id)#fetching the post and since we are getting sth by the id we can use the get command
    return render_template('post.html', title=post.title, post=post)

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
#you have to be logged in to be able to update
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)#this is a http response of a forbidden route
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        #since we are updating sth that is alraedy in the database we do not need to add we just commit
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

#this route is used to display the posts that are associated with a specific user

uavblog/users/routes.py
'''importing the relevant dependencies'''
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from uavblog import db, bcrypt
from uavblog.models import User, Post
from uavblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from uavblog.users.utils import save_picture, send_reset_email


#creating an instance of the blueprint just like for the flask app
users = Blueprint('users', __name__)


#remember to make the page to be able to accept other methods in the page
#this allows the routes to be more specific to the user as the route
@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()#creating an instance of the registration form
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')#this is a situation when you weant it to be a string rather than a byte
        user = User(tutor_username=form.tutor_username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f"Your Account has been created !You can now log in!","success")#this is the creation of a flash message with the second parameter in the message allowing you to have a category
        return redirect(url_for('users.login'))#this redirects one back to the homepage on registration with this being the function that is the home page
    return render_template('register.html', title='Register', form=form)



@users.route("/login",methods=["GET", "POST"])
#this allows the page to accept the post request that you send to it by filling data in the various fields
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data) 
            next_page = request.args.get('next')#args is a dictionary but avoid accessing next using the square brackets and key name as that would throw an error if the key name doesnt exist so just use the get method
            return redirect(next_page) if next_page else redirect(url_for('main.home'))#this is a ternary conditional in python
            #the part above just makes sure that if there is a next query on the url on page we can acquire it to directly take the user to the next page without having to take the user to another page and basically improves user experience 
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template("login.html", title="Login", form=form)
#if parameters dont match it returns one to the login page again

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
  form = UpdateAccountForm()
  if form.validate_on_submit():
    if form.picture.data:
      picture_file = save_picture(form.picture.data)
      current_user.image_file = picture_file
    current_user.tutor_username = form.tutor_username.data#made easier by using sql_Alchemy
    current_user.email = form.email.data
    db.session.commit()
    flash('Your account has been updated!', 'success')
    #getting an update on an account overwrites on the existent account
    return redirect(url_for('users.account'))
    #it is best that you do a redirect before you return a render as it results to no resubmission of posts method since a redirect sends out a get method instead of post
  elif request.method == 'GET':#this is used to populate the account in advance
    form.tutor_username.data = current_user.tutor_username
    form.email.data = current_user.email
    #this is the default path of the image_file
  image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
  #instead you could have used an f'string 
  return render_template('account.html', title='Account',
                           image_file=image_file, form=form)  
#this allows you to pass in the image file onto the accounts template as a variable image file

@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(tutor_username=username).first_or_404()#the parameter username is from the route that we get from the route function
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)#create a user_posts.html that handles all the posts for a specific user
#a backslash allows you to break a line into multiple lines

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)#inheritance from the model page
    if user is None:
        flash('That is an invalid or expired token', 'warning')#the tag on the message is a yellow one 
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

uavblog/templates/about.html
{% extends "layout.html" %}
<!-- inheriting from the layout.html -->
<!-- allowing the content in the body to be able to ovewrite what is in the block content -->
{% block content %}
	<h1>About page!</h1>
{% endblock content %}

uavblog/templates/accounts.html
<!-- this is the page where the user can upload their picture and also change their information -->
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
      	<!-- this is the image_file parameter set on the routes.py -->
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.tutor_username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
      <div class = "content-section">
		<form method ="POST" action ="" enctype="multipart/form-data">
			<!-- the encode type allows us to allow pictures as the input -->
			{{ form.hidden_tag() }}
			<fieldset  class ="form-group">
				<legend class = "border-bottom mb-4"> Account Information</legend>
				<div class = "form-group">
					{{ form.tutor_username.label(class = "form-control-label") }}
					{% if form.tutor_username.errors %}
						{{ form.tutor_username(class = "form-control form-control-lg is-invalid") }}
						<div class = "invalid-feedback">
							{% for error in form.tutor_username.errors %}
								<span>{{ error }}</span>
							{% endfor %}
							
						</div>
					{% else %}
						{{ form.tutor_username(class = "form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class = "form-group">
					{{ form.email.label(class = "form-control-label") }}
					{% if form.email.errors %}
						{{ form.email(class = "form-control form-control-lg is-invalid") }}
						<div class = "invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
							
						</div>
					{% else %}
						{{ form.email(class = "form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					<!-- creating a place in the form to acquire the images -->
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                            <!-- break allows us give the image some space -->
                        {% endfor %}
                    {% endif %}
                </div>
			</fieldset>
			<div class = "form-group">
					{{ form.submit.label(class = "btn btn-outline-info") }}
				</div>
				<small class = "text-muted ml-2">
					<a href="#">Forgot Password?</a>
				</small>
			
		</form>
    </div>
{% endblock content %}

uavblog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <!-- the legend as a variable is already mentioned in the routes.py -->
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

uavblog/templates/home.html
the sites home page ovewrite layout -->
{% extends "layout.html" %}
<!-- inheriting from the layout.html -->
<!-- allowing the content in the body to be able to ovewrite what is in the block content -->
{% block content %}
	{% for post in posts.items %}
  <!-- the main reason why we include the dot items is because now this is a pagination object -->
  <!-- look at the first tutorial for the original code though it was less appealing but atleast you could input large sums of data -->
		<article class="media content-section">
          <img class =''rounded-circle article-img'' src="{{ url_for(''static'', filename=''procfile_pics/'' + post.author.image_file) }}">
          <!-- the author is a backref that gives us access to the user and all their attributes thius even acquiring the image attached to that user -->
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('user.user_posts', username=post.author.tutor_username) }}">{{ post.author.tutor_username }}</a>
              <!-- just print out the users username instead of printing out the whole user object -->
              <small class="text-muted">{{ post.date_posted.strftime(''%Y-%m-%d'') }}</small>
              <!-- this allows you to be able to display the time the post was created in a specific way -->
              <!-- the templating engine that flask uses is jinja 2 which allows the use of code blocks-->
              <!-- printing a variable is not the same as a code block so you use double curly braces -->
            </div>
            <h2><a class="article-title" href="{{url_for ('posts.post',post_id = post.id)}}">{{ post.title }}</a></h2>
            <!-- the reason why the above line is a href is so as to be able to link to the post html page that is being created -->
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
	{% endfor %}
  <!-- creating links to the pages that we want and the class is just for aesthetics -->
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  <!-- the code in the brackets reduces the amount of page links that are going to be highelighted -->
      {% if page_num %}
        {% if posts.page == page_num %}
          <!-- using bootstrap the btn btn-info without an outline just outlines the selected page with a dark colour -->
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}
<!-- jinja 2 allows you to put the name of the block that you want to overwrite in the end of the code block -->

uavblog/templates/layout.html
<!-- the index html from which all the pages inherit -->
<!DOCTYPE html>
<html>
<head>
  <!-- the block is a part of the code that the child templates can overwrite -->
	<!-- this serves as or parent template from which all will inherit from ,that is,it allows template inheritance-->
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for("static", filename="main.css") }}">
    <!-- this links main.css in the static to the main css since url helps you to locate the actual locatio of the url -->

	{% if title %}
		<title>Unmanned Aerial Vehicle Design -{{ title }}</title>		
	{% else %}
		<title>Unmanned Aerial Vehicle Design</title>
	{% endif %}
</head>
<body>
	<!-- boostrap code for a responsive page on smaller sized screens-->
	<header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Unmanned Aerial Vehicle Design Learning</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
              <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
	<main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          <!-- the below function will help you to be able to acquire the flash messages and display them in each of your pages  -->
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
          <!-- this is the point at which the overwrite is going to take place in the othe template pages. -->
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class="text-muted">You will find additional information related to the course here.
              <ul class="list-group">
              	<li class="list-group-item list-group-item-light">Tutors</li>
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>
	<!-- we aregoing to use a code block that can enable inheritance -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>
<!-- used in the case of template inheritance -->

uavblog/templates/login.html
<!-- ovewrite of the layout template with login form -->
{% extends "layout.html" %}
<!-- inheriting from the layout.html -->
<!-- allowing the content in the body to be able to ovewrite what is in the block content -->
<!-- content section is a style that is already available in the main.css -->
<!-- the below method of post and then an empty string means that when this form is posted it goes to the same route that we are currently i -->
<!-- the hidden _tag is used to ensure CSRF as a security measure -->
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                    <!-- this is a dummy url for now so as to be able to control how one is resent a re-registration -->
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for("users.register") }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}
<!-- the above url for remember returns the function name that is highlighted as login in the uav_blog.py -->

uavblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='procfile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.tutor_username) }}">{{ post.author.tutor_username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <!-- sm means small for the bootstrap button that we want to place in the page -->
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            <!-- a modal is actually a pop up that blurs everything on the page withits pop up leaving it as the only visible page and you should take care of the places within the creation of the modal to make sure that they all conform to delete modal -->
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  <!-- Modal -->
  <!-- responsible for the modal pop up -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

uavblog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.tutor_username }} ({{ posts.total }})</h1>

    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.tutor_username) }}">{{ post.author.tutor_username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.tutor_username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.tutor_username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}